---
title: "CBDRH_demo"
author: "A.T. du Toit"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
library(knitr)
library(kableExtra)
library(janitor)
library(caroline)

mk <- function(x) {
    kable(x) %>% kable_styling(bootstrap_options = c("striped", "hover", "condensed"))
}

```


```{r Create: table and kable functions for examples}
tabl_fun <- function(tabl) {
  tabl %<>% rename(var1 = 1) 
  tabl %<>% adorn_totals(c("col"))
  tab_data_colnames <- colnames(tabl)
  tab_data_colnames <- tab_data_colnames[2:length(tab_data_colnames)]
  tabl %<>% pct(c(tab_data_colnames))
  tabl %<>% adorn_totals("row") 
  tab_pct_colnames <- tabl %>% select(ends_with(".pct")) %>% colnames()
  tabl %<>% adorn_pct_formatting(,,,all_of(c(tab_pct_colnames)))            # need to remove all_of()
  tab_data_and_pct_colnames <- as.vector(rbind(tab_data_colnames,tab_pct_colnames))
  tabl %<>% select(var1, all_of(tab_data_and_pct_colnames))                 # remove all_of()
  } 

kable_tabl_fun <- function(tabl) {
    tabl %<>% kable(col.names = c(all_of(col1), "n", "%", "n", "%","n", "%","n", "%"),
         align = "lrrrrrrrr") %>%
   kable_styling(htmltable_class = "lightable-classic-2", full_width = FALSE) %>% 
    column_spec(1, width = "4cm") %>%
    column_spec(c(2,4,6,8), width = "0.8cm") %>%
    column_spec(c(3,5,7,9), width = "2cm") %>%
    row_spec(0, bold = T) %>% 
    row_spec(nrow(tabl), bold = T) %>% 
  add_header_above(c(" "=1, "Fresh"=2, "Thawed"=2, "Oocyte/Embryo \n recipient"=2, "All"=2), align = "c", bold = TRUE) %>% 
  add_header_above(c(" "=1, "Autologous"=4, " "=4), bold = TRUE)
  } 
```

```{r Create: dummy data}
dummy_data1 <- data.frame(
  PAT_ID = c(1:56),
  PARENT_SEX = c(rep(1, 46), rep(2, 8), rep(3, 2)),
  FAGE = rnorm(56, mean = 36, sd = 3.5)
  )

dummy_data1$FAGE[which.max(dummy_data1$FAGE)] <- 46 # max age is always 46 so all age breaks filled
dummy_data1$FAGE[which.min(dummy_data1$FAGE)] <- 28 # min age is always 28 so all age breaks filled

dummy_data1 %<>% mutate(FAGE_BIN = cut(FAGE, breaks = c(0,30,34,39,44,100), include.lowest = TRUE, labels = c("\u003c 30", "30-34", "35-39", "40-44", "\u2265 45")))
 
# create and randomise some vectors for use in data frame
n_v_egth1 <- c(rep(0, 53), rep(1, 36))
n_v_egth1 <- sample(n_v_egth1)
n_v_egth1 <- c(n_v_egth1, rep(NA, 2))

n_v_egth2 <- c(rep(0, 10), rep(1, 2))
n_v_egth2 <- sample(n_v_egth2)
n_v_egth2 <- c(n_v_egth2, rep(NA, 1))

n_v_egth3 <- c(rep(0, 2), rep(1, 1))
n_v_egth3 <- sample(n_v_egth3)
n_v_egth3 <- c(n_v_egth3, rep(NA, 1))

n_v_egth <- c(n_v_egth1, n_v_egth2, n_v_egth3)
  
dummy_data2 <- data.frame(
  PAT_ID = c(1:18, rep(19:34,each=2), rep(35:41, each=3), rep(42:46, each=4), 
             47:50, rep(51:53, each=2), rep(54, each=3),
             rep(55:56, each=2)),
  CYCLE_ID = c(1:108), 
  CYCLE_TYPE = c(rep(1,89), 4, 5, rep(1, 12), 4, rep(1, 3), 5),   
  N_V_EGTH = c(n_v_egth)
      )

dummy_data <- right_join(dummy_data1, dummy_data2, by = "PAT_ID") 

rm(n_v_egth, n_v_egth1, n_v_egth2, n_v_egth3, dummy_data1, dummy_data2)   
```

```{r Create: example table 2 using function}
tab2 <- dummy_data %>% tabyl(PARENT_SEX, N_V_EGTH) %>% tabl_fun() 
col1 <- "Intending parents"   

tab2 %>% 
  mutate(var1 = case_when(var1 == "1" ~ "Female-male couple",
      var1 == "2" ~ "Single female",
      var1 == "3" ~ "Female-female couple",
       .default = as.character(var1))) %>%
  kable_tabl_fun() %>% 
    add_header_above(c("Table 2: Number of autologous and recipient cycles by intending parents and treatment type, Australia and New Zealand, 2021"=9), bold = TRUE, align = "l")  

```

```{r Create: example table 3 using function}
tab3 <- dummy_data %>% tabyl(FAGE_BIN, N_V_EGTH) %>% tabl_fun()   
col1 <- "Age group (years) (a)"   

tab3 %>% 
  kable_tabl_fun() %>% 
  add_header_above(c("Table 3: Number of autologous and recipient cycles by female patient age and treatment type, Australia and New Zealand, 2021"=9), bold = TRUE, align = "l") %>% 
  footnote(c("(a) Age at start of a treatment cycle.", "Data are collected for each treatment cycle; therefore, some individuals may be counted more than once."))  
  
```

```{r Stop running code}
knit_exit()   

# Deprecated code below here
```

```{r Create: make columns of percentages}
# tab2 %<>% 
#   mutate(`0_pct` = `0` / last(`0`), .after = `0`) %>% 
#   mutate(`1_pct` = `1` / last(`1`), .after = `1`) %>% 
#   mutate(`NA_pct` = `NA_` / last(`NA_`), .after = `NA_`) %>% 
#   mutate(Total_pct = Total / last(Total), .after = `Total`)  

```

```{r Create: example table}
# tab2 <- dummy_data %>% tabyl(PARENT_SEX, N_V_EGTH) 
# 
# tab2 %<>% rename(var1 = 1) 
# tab2 %<>% adorn_totals(c("col"))
# 
# tab_data_colnames <- colnames(tab2)
# tab_data_colnames <- tab_data_colnames[2:length(tab_data_colnames)]
# 
# tab2 %<>% pct(c(tab_data_colnames))
# tab2 %<>% adorn_totals("row") 
# 
# tab_pct_colnames <- tab2 %>% select(ends_with(".pct")) %>% colnames()
# 
# tab2 %<>% adorn_pct_formatting(,,,all_of(c(tab_pct_colnames)))
# 
# tab_data_and_pct_colnames <- as.vector(rbind(tab_data_colnames,tab_pct_colnames))
# 
# tab2 %<>% select(var1, all_of(tab_data_and_pct_colnames))
# 
# 
# tab2 %>% 
#   mutate(var1 = case_when(var1 == "1" ~ "Female-male couple",
#       var1 == "2" ~ "Single female",
#       var1 == "3" ~ "Female-female couple",
#        .default = as.character(var1))) %>%
#    kable(col.names = c("Intending parents", "n", "%", "n", "%","n", "%","n", "%"),
#          align = "lrrrrrrrr") %>%
#    kable_styling(htmltable_class = "lightable-classic-2") %>% 
#   row_spec(nrow(tab2), bold = T) %>% 
#   add_header_above(c(" "=1, "Fresh"=2, "Thawed"=2, "Oocyte/Embryo \n recipient"=2, "All"=2), align = "c") %>% 
#   add_header_above(c(" "=1, "Autologous"=4, " "=4)) %>% 
#   add_header_above(c("Table 2: Number of autologous and recipient cycles by intending parents and treatment type, Australia and New Zealand, 2021"=9), bold = TRUE, align = "l")  

```

```{r Create: example table 2 using function old version}
# tab2 %>% 
#   mutate(var1 = case_when(var1 == "1" ~ "Female-male couple",
#       var1 == "2" ~ "Single female",
#       var1 == "3" ~ "Female-female couple",
#        .default = as.character(var1))) %>%
#    kable(col.names = c("Intending parents", "n", "%", "n", "%","n", "%","n", "%"),
#          align = "lrrrrrrrr") %>%
#    kable_styling(htmltable_class = "lightable-classic-2",
#                  full_width = FALSE) %>% 
#     column_spec(1, width = "4.5cm") %>%
#     column_spec(c(2,4,6,8), width = "0.8cm") %>%
#     column_spec(c(3,5,7,9), width = "2cm") %>%
#     row_spec(0, bold = T) %>% 
#     row_spec(nrow(tab2), bold = T) %>% 
#   add_header_above(c(" "=1, "Fresh"=2, "Thawed"=2, "Oocyte/Embryo \n recipient"=2, "All"=2), align = "c", bold = TRUE) %>% 
#   add_header_above(c(" "=1, "Autologous"=4, " "=4), bold = TRUE) %>% 
#   add_header_above(c("Table 2: Number of autologous and recipient cycles by intending parents and treatment type, Australia and New Zealand, 2021"=9), bold = TRUE, align = "l")  

```

```{r Create: example table 3 using function old version}
# tab3 %>% 
#    kable(col.names = c(all_of(col1), "n", "%", "n", "%","n", "%","n", "%"),
#          align = "lrrrrrrrr") %>%
#    kable_styling(htmltable_class = "lightable-classic-2",
#                  full_width = FALSE) %>% 
#     column_spec(1, width = "4cm") %>%
#     column_spec(c(2,4,6,8), width = "0.8cm") %>%
#     column_spec(c(3,5,7,9), width = "2cm") %>%
#     row_spec(0, bold = T) %>% 
#     row_spec(nrow(tab3), bold = T) %>% 
#   add_header_above(c(" "=1, "Fresh"=2, "Thawed"=2, "Oocyte/Embryo \n recipient"=2, "All"=2), align = "c", bold = TRUE) %>% 
#   add_header_above(c(" "=1, "Autologous"=4, " "=4), bold = TRUE) %>% 
#   add_header_above(c("Table 3: Number of autologous and recipient cycles by female patient age and treatment type, Australia and New Zealand, 2021"=9), bold = TRUE, align = "l") %>% 
#   footnote(c("(a) Age at start of a treatment cycle.", "Data are collected for each treatment cycle; therefore, some individuals may be counted more than once."))
```